name: CI
on: 
  push:
    branches-ignore:
     # we do NOT build the documentation branch, because here we only copy build output 
     # of documentation from master branch to the corresponding doc folders -e.g. /docs/latest
     # So this branch is only for github pages. 
     - documentation
     # We ignore everything where tag starts with v* - this is done by release build!
    tags-ignore:
     - v*

jobs:
  build:

    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    with:
      node-version: '14'
    - run: npm install
    - run: npm test
